title: Blog da Primária
description: Blog com as principais novidades para fotovoltaica, instalações elétricas e a reaproveitamento de água
url: "primariaenergia.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog

# Comments
discus_identifier: mr-brown

# Social settings
twitter_url: https://twitter.com/artemsheludko_
facebook_url: https://facebook.com/primariaenergia.com
googleplus_url: https://plus.google.com/
instagram_url: https://instagram.com
github_url: https://github.com/artemsheludko/
facebook_like: false  
